### ISSUE TITLE
Check Please .... 

### ISSUE THREAD

**Issue by mamuna2m** [dmamontov/davbackup#3]
Hi,
How are you?
I am using your davbackup and it's awesome. You made a great class that helped me a lot. Thanks to you for your work.

I need some information  from you.... 
I want to use the .rar extension and in your class you mentioned about the .rar extension and there need an another class from https://github.com/dmamontov/rararchiver

Can you please tell me that how can I integrate this class with your class that you made https://github.com/dmamontov/davbackup

and one more thing ... In your class you managed the database export system in .sql formate. If I want to use another system like(.zip, .gzip).... is it possible ??

Hope that you will got my point.... Waiting for your reply and Thanks again :) :) :)

**Comment by dmamontov** [comment]
Good afternoon! All is well!
To work with rar required by composer set 2 libraries:

``` sh
composer require dmamontov/davbackup ~1.1.0
composer require dmamontov/rararchiver ~1.0.0
```

The class is not intended to form the base of a compressed dump. If you need this functionality. I can add. But in this case it will not work on servers where prohibited exec.

**Comment by mamuna2m** [comment]
Thanks, I will try to set 2 libraries.

and one more thing ... In your class you managed the database export system in .sql formate. If I want to use another system like(.zip, .gzip).... is it possible ??

Waiting for your reply and Thanks again :) :) :)
